= Cheatsheets

[[TemplateEngineEntry]]
== TemplateEngineEntry

++++
 Describes a details of template engine.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[config]]`@config`|`Json object`|+++
Sets <code>io.knotx.te.api.TemplateEngine</code> implementation configuration.
+++
|[[factory]]`@factory`|`String`|+++
Sets the template engine factory name. This name would be used to get the <code>TemplateEngineFactory</code> that provides the Template Engine
+++
|===

[[TemplateEngineKnotOptions]]
== TemplateEngineKnotOptions

++++
 Describes Template Engine configuration
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[address]]`@address`|`String`|+++
Sets the EB address of the Verticle. Default is <code>"knotx.knot.te"</code>.
+++
|[[engine]]`@engine`|`link:dataobjects.html#TemplateEngineEntry[TemplateEngineEntry]`|+++
Sets the template engine strategy for this Knot instance. This template engine will be used
 every time Fragment is processed by this Knot.
+++
|===

